//
//  InterfaceButtons.m
//  Gather
//
//  Created by Brandon Beecroft on 10/22/14.
//  Copyright (c) 2014 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "InterfaceButtons.h"


@implementation InterfaceButtons

#pragma mark Cache

static UIColor* _snowWhite = nil;

static UIImage* _imageOfPhoto = nil;
static UIImage* _imageOfFamilyFriendsIcon = nil;
static UIImage* _imageOfInviteIcon = nil;
static UIImage* _imageOfTimeline = nil;

#pragma mark Initialization

+ (void)initialize
{
    // Colors Initialization
    _snowWhite = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];

}

#pragma mark Colors

+ (UIColor*)snowWhite { return _snowWhite; }

#pragma mark Drawing Methods

+ (void)drawPhoto
{
    //// Color Declarations
    UIColor* color2 = [UIColor colorWithRed: 0.156 green: 0.744 blue: 0.759 alpha: 0.25];

    //// Page-1
    {
        //// Oval-34-+-Imported-Layers
        {
            //// Oval-34 Drawing
            UIBezierPath* oval34Path = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(5, 5, 90, 90)];
            [color2 setFill];
            [oval34Path fill];
            [InterfaceButtons.snowWhite setStroke];
            oval34Path.lineWidth = 3;
            [oval34Path stroke];


            //// Imported-Layers Drawing
            UIBezierPath* importedLayersPath = UIBezierPath.bezierPath;
            [importedLayersPath moveToPoint: CGPointMake(71.86, 35.13)];
            [importedLayersPath addLineToPoint: CGPointMake(66.43, 35.13)];
            [importedLayersPath addCurveToPoint: CGPointMake(64.08, 32.79) controlPoint1: CGPointMake(65.13, 35.13) controlPoint2: CGPointMake(64.08, 34.08)];
            [importedLayersPath addLineToPoint: CGPointMake(64.08, 31.62)];
            [importedLayersPath addCurveToPoint: CGPointMake(58.86, 26.43) controlPoint1: CGPointMake(64.08, 28.76) controlPoint2: CGPointMake(61.74, 26.43)];
            [importedLayersPath addLineToPoint: CGPointMake(41.96, 26.43)];
            [importedLayersPath addCurveToPoint: CGPointMake(36.75, 31.62) controlPoint1: CGPointMake(39.09, 26.43) controlPoint2: CGPointMake(36.75, 28.76)];
            [importedLayersPath addLineToPoint: CGPointMake(36.75, 32.79)];
            [importedLayersPath addCurveToPoint: CGPointMake(34.4, 35.13) controlPoint1: CGPointMake(36.75, 34.08) controlPoint2: CGPointMake(35.7, 35.13)];
            [importedLayersPath addLineToPoint: CGPointMake(28.96, 35.13)];
            [importedLayersPath addCurveToPoint: CGPointMake(23.75, 40.31) controlPoint1: CGPointMake(26.09, 35.13) controlPoint2: CGPointMake(23.75, 37.45)];
            [importedLayersPath addLineToPoint: CGPointMake(23.75, 64.76)];
            [importedLayersPath addCurveToPoint: CGPointMake(28.96, 69.95) controlPoint1: CGPointMake(23.75, 67.62) controlPoint2: CGPointMake(26.09, 69.95)];
            [importedLayersPath addLineToPoint: CGPointMake(71.86, 69.95)];
            [importedLayersPath addCurveToPoint: CGPointMake(77.08, 64.76) controlPoint1: CGPointMake(74.74, 69.95) controlPoint2: CGPointMake(77.08, 67.62)];
            [importedLayersPath addLineToPoint: CGPointMake(77.08, 40.31)];
            [importedLayersPath addCurveToPoint: CGPointMake(71.86, 35.13) controlPoint1: CGPointMake(77.08, 37.45) controlPoint2: CGPointMake(74.74, 35.13)];
            [importedLayersPath addLineToPoint: CGPointMake(71.86, 35.13)];
            [importedLayersPath closePath];
            [importedLayersPath moveToPoint: CGPointMake(74.22, 64.76)];
            [importedLayersPath addCurveToPoint: CGPointMake(71.86, 67.1) controlPoint1: CGPointMake(74.22, 66.05) controlPoint2: CGPointMake(73.16, 67.1)];
            [importedLayersPath addLineToPoint: CGPointMake(28.96, 67.1)];
            [importedLayersPath addCurveToPoint: CGPointMake(26.61, 64.76) controlPoint1: CGPointMake(27.67, 67.1) controlPoint2: CGPointMake(26.61, 66.05)];
            [importedLayersPath addLineToPoint: CGPointMake(26.61, 40.31)];
            [importedLayersPath addCurveToPoint: CGPointMake(28.96, 37.97) controlPoint1: CGPointMake(26.61, 39.02) controlPoint2: CGPointMake(27.67, 37.97)];
            [importedLayersPath addLineToPoint: CGPointMake(34.4, 37.97)];
            [importedLayersPath addCurveToPoint: CGPointMake(39.61, 32.79) controlPoint1: CGPointMake(37.27, 37.97) controlPoint2: CGPointMake(39.61, 35.65)];
            [importedLayersPath addLineToPoint: CGPointMake(39.61, 31.62)];
            [importedLayersPath addCurveToPoint: CGPointMake(41.96, 29.28) controlPoint1: CGPointMake(39.61, 30.33) controlPoint2: CGPointMake(40.67, 29.28)];
            [importedLayersPath addLineToPoint: CGPointMake(58.86, 29.28)];
            [importedLayersPath addCurveToPoint: CGPointMake(61.22, 31.62) controlPoint1: CGPointMake(60.16, 29.28) controlPoint2: CGPointMake(61.22, 30.33)];
            [importedLayersPath addLineToPoint: CGPointMake(61.22, 32.79)];
            [importedLayersPath addCurveToPoint: CGPointMake(66.43, 37.97) controlPoint1: CGPointMake(61.22, 35.65) controlPoint2: CGPointMake(63.55, 37.97)];
            [importedLayersPath addLineToPoint: CGPointMake(71.86, 37.97)];
            [importedLayersPath addCurveToPoint: CGPointMake(74.22, 40.31) controlPoint1: CGPointMake(73.16, 37.97) controlPoint2: CGPointMake(74.22, 39.02)];
            [importedLayersPath addLineToPoint: CGPointMake(74.22, 64.76)];
            [importedLayersPath addLineToPoint: CGPointMake(74.22, 64.76)];
            [importedLayersPath closePath];
            [importedLayersPath moveToPoint: CGPointMake(50.41, 37.99)];
            [importedLayersPath addCurveToPoint: CGPointMake(38.76, 49.58) controlPoint1: CGPointMake(43.99, 37.99) controlPoint2: CGPointMake(38.76, 43.19)];
            [importedLayersPath addCurveToPoint: CGPointMake(50.41, 61.18) controlPoint1: CGPointMake(38.76, 55.98) controlPoint2: CGPointMake(43.99, 61.18)];
            [importedLayersPath addCurveToPoint: CGPointMake(62.07, 49.58) controlPoint1: CGPointMake(56.84, 61.18) controlPoint2: CGPointMake(62.07, 55.98)];
            [importedLayersPath addCurveToPoint: CGPointMake(50.41, 37.99) controlPoint1: CGPointMake(62.07, 43.19) controlPoint2: CGPointMake(56.84, 37.99)];
            [importedLayersPath addLineToPoint: CGPointMake(50.41, 37.99)];
            [importedLayersPath closePath];
            [importedLayersPath moveToPoint: CGPointMake(50.41, 58.33)];
            [importedLayersPath addCurveToPoint: CGPointMake(41.62, 49.58) controlPoint1: CGPointMake(45.57, 58.33) controlPoint2: CGPointMake(41.62, 54.41)];
            [importedLayersPath addCurveToPoint: CGPointMake(50.41, 40.84) controlPoint1: CGPointMake(41.62, 44.76) controlPoint2: CGPointMake(45.57, 40.84)];
            [importedLayersPath addCurveToPoint: CGPointMake(59.21, 49.58) controlPoint1: CGPointMake(55.26, 40.84) controlPoint2: CGPointMake(59.21, 44.76)];
            [importedLayersPath addCurveToPoint: CGPointMake(50.41, 58.33) controlPoint1: CGPointMake(59.21, 54.41) controlPoint2: CGPointMake(55.26, 58.33)];
            [importedLayersPath addLineToPoint: CGPointMake(50.41, 58.33)];
            [importedLayersPath closePath];
            [importedLayersPath moveToPoint: CGPointMake(67.69, 42.62)];
            [importedLayersPath addCurveToPoint: CGPointMake(65.24, 45.06) controlPoint1: CGPointMake(66.34, 42.62) controlPoint2: CGPointMake(65.24, 43.71)];
            [importedLayersPath addCurveToPoint: CGPointMake(67.69, 47.5) controlPoint1: CGPointMake(65.24, 46.41) controlPoint2: CGPointMake(66.34, 47.5)];
            [importedLayersPath addCurveToPoint: CGPointMake(70.14, 45.06) controlPoint1: CGPointMake(69.05, 47.5) controlPoint2: CGPointMake(70.14, 46.41)];
            [importedLayersPath addCurveToPoint: CGPointMake(67.69, 42.62) controlPoint1: CGPointMake(70.14, 43.71) controlPoint2: CGPointMake(69.05, 42.62)];
            [importedLayersPath addLineToPoint: CGPointMake(67.69, 42.62)];
            [importedLayersPath closePath];
            importedLayersPath.miterLimit = 4;

            importedLayersPath.usesEvenOddFillRule = YES;

            [InterfaceButtons.snowWhite setFill];
            [importedLayersPath fill];
        }
    }
}

+ (void)drawFamilyFriendsIcon
{
    //// Color Declarations
    UIColor* color5 = [UIColor colorWithRed: 0.1 green: 0.789 blue: 0.877 alpha: 0.15];
    UIColor* color6 = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];

    //// Page-1
    {
        //// Initial-ADD
        {
            //// familyFriendsIcon
            {
                //// Oval-34 Drawing
                UIBezierPath* oval34Path = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(5, 5, 90, 90)];
                [color5 setFill];
                [oval34Path fill];
                [color6 setStroke];
                oval34Path.lineWidth = 3;
                [oval34Path stroke];


                //// Imported-Layers Drawing
                UIBezierPath* importedLayersPath = UIBezierPath.bezierPath;
                [importedLayersPath moveToPoint: CGPointMake(73.97, 72.03)];
                [importedLayersPath addLineToPoint: CGPointMake(59.03, 56.98)];
                [importedLayersPath addCurveToPoint: CGPointMake(63.33, 44.81) controlPoint1: CGPointMake(61.72, 53.66) controlPoint2: CGPointMake(63.33, 49.42)];
                [importedLayersPath addCurveToPoint: CGPointMake(44.17, 25.5) controlPoint1: CGPointMake(63.33, 34.16) controlPoint2: CGPointMake(54.73, 25.5)];
                [importedLayersPath addCurveToPoint: CGPointMake(25, 44.81) controlPoint1: CGPointMake(33.6, 25.5) controlPoint2: CGPointMake(25, 34.16)];
                [importedLayersPath addCurveToPoint: CGPointMake(44.17, 64.11) controlPoint1: CGPointMake(25, 55.45) controlPoint2: CGPointMake(33.6, 64.11)];
                [importedLayersPath addCurveToPoint: CGPointMake(56.95, 59.18) controlPoint1: CGPointMake(49.07, 64.11) controlPoint2: CGPointMake(53.55, 62.24)];
                [importedLayersPath addLineToPoint: CGPointMake(71.84, 74.18)];
                [importedLayersPath addCurveToPoint: CGPointMake(74.12, 74.34) controlPoint1: CGPointMake(72.51, 74.86) controlPoint2: CGPointMake(73.54, 74.93)];
                [importedLayersPath addCurveToPoint: CGPointMake(73.97, 72.03) controlPoint1: CGPointMake(74.71, 73.74) controlPoint2: CGPointMake(74.64, 72.71)];
                [importedLayersPath addLineToPoint: CGPointMake(73.97, 72.03)];
                [importedLayersPath closePath];
                [importedLayersPath moveToPoint: CGPointMake(44.17, 61.07)];
                [importedLayersPath addCurveToPoint: CGPointMake(28.02, 44.81) controlPoint1: CGPointMake(35.26, 61.07) controlPoint2: CGPointMake(28.02, 53.78)];
                [importedLayersPath addCurveToPoint: CGPointMake(44.17, 28.54) controlPoint1: CGPointMake(28.02, 35.84) controlPoint2: CGPointMake(35.26, 28.54)];
                [importedLayersPath addCurveToPoint: CGPointMake(60.31, 44.81) controlPoint1: CGPointMake(53.07, 28.54) controlPoint2: CGPointMake(60.31, 35.84)];
                [importedLayersPath addCurveToPoint: CGPointMake(44.17, 61.07) controlPoint1: CGPointMake(60.31, 53.78) controlPoint2: CGPointMake(53.07, 61.07)];
                [importedLayersPath addLineToPoint: CGPointMake(44.17, 61.07)];
                [importedLayersPath closePath];
                [importedLayersPath moveToPoint: CGPointMake(44.17, 47.02)];
                [importedLayersPath addCurveToPoint: CGPointMake(36.61, 51.5) controlPoint1: CGPointMake(40.93, 47.02) controlPoint2: CGPointMake(38.1, 48.83)];
                [importedLayersPath addCurveToPoint: CGPointMake(36.34, 52.36) controlPoint1: CGPointMake(36.44, 51.75) controlPoint2: CGPointMake(36.34, 52.04)];
                [importedLayersPath addCurveToPoint: CGPointMake(36.85, 53.49) controlPoint1: CGPointMake(36.34, 52.8) controlPoint2: CGPointMake(36.56, 53.18)];
                [importedLayersPath addCurveToPoint: CGPointMake(37.82, 54.35) controlPoint1: CGPointMake(37.14, 53.81) controlPoint2: CGPointMake(37.48, 54.09)];
                [importedLayersPath addCurveToPoint: CGPointMake(40.1, 55.7) controlPoint1: CGPointMake(38.52, 54.9) controlPoint2: CGPointMake(39.29, 55.35)];
                [importedLayersPath addCurveToPoint: CGPointMake(42.69, 56.42) controlPoint1: CGPointMake(40.93, 56.05) controlPoint2: CGPointMake(41.8, 56.3)];
                [importedLayersPath addCurveToPoint: CGPointMake(44.17, 56.53) controlPoint1: CGPointMake(43.18, 56.49) controlPoint2: CGPointMake(43.67, 56.53)];
                [importedLayersPath addCurveToPoint: CGPointMake(51.54, 53.45) controlPoint1: CGPointMake(47.04, 56.53) controlPoint2: CGPointMake(49.65, 55.35)];
                [importedLayersPath addCurveToPoint: CGPointMake(51.99, 52.36) controlPoint1: CGPointMake(51.82, 53.17) controlPoint2: CGPointMake(51.99, 52.79)];
                [importedLayersPath addCurveToPoint: CGPointMake(51.72, 51.5) controlPoint1: CGPointMake(51.99, 52.04) controlPoint2: CGPointMake(51.89, 51.74)];
                [importedLayersPath addCurveToPoint: CGPointMake(44.17, 47.02) controlPoint1: CGPointMake(50.23, 48.83) controlPoint2: CGPointMake(47.4, 47.02)];
                [importedLayersPath addLineToPoint: CGPointMake(44.17, 47.02)];
                [importedLayersPath closePath];
                [importedLayersPath moveToPoint: CGPointMake(44.17, 45.56)];
                [importedLayersPath addCurveToPoint: CGPointMake(48.5, 41.19) controlPoint1: CGPointMake(46.55, 45.56) controlPoint2: CGPointMake(48.5, 43.59)];
                [importedLayersPath addLineToPoint: CGPointMake(48.5, 38.28)];
                [importedLayersPath addCurveToPoint: CGPointMake(44.17, 33.91) controlPoint1: CGPointMake(48.5, 35.87) controlPoint2: CGPointMake(46.55, 33.91)];
                [importedLayersPath addCurveToPoint: CGPointMake(39.83, 38.28) controlPoint1: CGPointMake(41.78, 33.91) controlPoint2: CGPointMake(39.83, 35.87)];
                [importedLayersPath addLineToPoint: CGPointMake(39.83, 41.19)];
                [importedLayersPath addCurveToPoint: CGPointMake(44.17, 45.56) controlPoint1: CGPointMake(39.83, 43.59) controlPoint2: CGPointMake(41.78, 45.56)];
                [importedLayersPath addLineToPoint: CGPointMake(44.17, 45.56)];
                [importedLayersPath closePath];
                importedLayersPath.miterLimit = 4;

                importedLayersPath.usesEvenOddFillRule = YES;

                [color6 setFill];
                [importedLayersPath fill];
            }
        }
    }
}

+ (void)drawInviteIcon
{
    //// Color Declarations
    UIColor* color8 = [UIColor colorWithRed: 0.1 green: 0.789 blue: 0.877 alpha: 0.15];
    UIColor* color9 = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];

    //// Page-1
    {
        //// Initial-ADD
        {
            //// inviteIcon
            {
                //// Oval-34 Drawing
                UIBezierPath* oval34Path = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(5, 5, 90, 90)];
                [color8 setFill];
                [oval34Path fill];
                [color9 setStroke];
                oval34Path.lineWidth = 3;
                [oval34Path stroke];


                //// Imported-Layers Drawing
                UIBezierPath* importedLayersPath = UIBezierPath.bezierPath;
                [importedLayersPath moveToPoint: CGPointMake(70.1, 50.86)];
                [importedLayersPath addCurveToPoint: CGPointMake(74.29, 44.7) controlPoint1: CGPointMake(72.55, 49.88) controlPoint2: CGPointMake(74.29, 47.49)];
                [importedLayersPath addLineToPoint: CGPointMake(74.29, 41.12)];
                [importedLayersPath addCurveToPoint: CGPointMake(67.68, 34.5) controlPoint1: CGPointMake(74.29, 37.47) controlPoint2: CGPointMake(71.32, 34.5)];
                [importedLayersPath addCurveToPoint: CGPointMake(61.07, 41.12) controlPoint1: CGPointMake(64.04, 34.5) controlPoint2: CGPointMake(61.07, 37.47)];
                [importedLayersPath addLineToPoint: CGPointMake(61.07, 44.7)];
                [importedLayersPath addCurveToPoint: CGPointMake(65.27, 50.86) controlPoint1: CGPointMake(61.07, 47.5) controlPoint2: CGPointMake(62.82, 49.89)];
                [importedLayersPath addCurveToPoint: CGPointMake(60.47, 53.04) controlPoint1: CGPointMake(63.54, 51.22) controlPoint2: CGPointMake(61.91, 51.95)];
                [importedLayersPath addCurveToPoint: CGPointMake(60.46, 53.05) controlPoint1: CGPointMake(60.47, 53.04) controlPoint2: CGPointMake(60.46, 53.05)];
                [importedLayersPath addCurveToPoint: CGPointMake(61.96, 55.05) controlPoint1: CGPointMake(61.01, 53.67) controlPoint2: CGPointMake(61.51, 54.34)];
                [importedLayersPath addCurveToPoint: CGPointMake(61.98, 55.04) controlPoint1: CGPointMake(61.96, 55.05) controlPoint2: CGPointMake(61.97, 55.04)];
                [importedLayersPath addCurveToPoint: CGPointMake(67.68, 53.11) controlPoint1: CGPointMake(63.64, 53.78) controlPoint2: CGPointMake(65.61, 53.11)];
                [importedLayersPath addCurveToPoint: CGPointMake(77.14, 62.6) controlPoint1: CGPointMake(72.9, 53.11) controlPoint2: CGPointMake(77.14, 57.37)];
                [importedLayersPath addCurveToPoint: CGPointMake(76.61, 63.14) controlPoint1: CGPointMake(77.14, 62.89) controlPoint2: CGPointMake(76.9, 63.14)];
                [importedLayersPath addLineToPoint: CGPointMake(64.08, 63.14)];
                [importedLayersPath addCurveToPoint: CGPointMake(63.24, 65.52) controlPoint1: CGPointMake(63.99, 64.01) controlPoint2: CGPointMake(63.69, 64.82)];
                [importedLayersPath addCurveToPoint: CGPointMake(63.76, 65.64) controlPoint1: CGPointMake(63.4, 65.6) controlPoint2: CGPointMake(63.58, 65.64)];
                [importedLayersPath addLineToPoint: CGPointMake(76.61, 65.64)];
                [importedLayersPath addCurveToPoint: CGPointMake(79.64, 62.6) controlPoint1: CGPointMake(78.28, 65.64) controlPoint2: CGPointMake(79.64, 64.28)];
                [importedLayersPath addCurveToPoint: CGPointMake(70.1, 50.86) controlPoint1: CGPointMake(79.64, 56.82) controlPoint2: CGPointMake(75.54, 51.98)];
                [importedLayersPath addLineToPoint: CGPointMake(70.1, 50.86)];
                [importedLayersPath closePath];
                [importedLayersPath moveToPoint: CGPointMake(63.57, 44.7)];
                [importedLayersPath addLineToPoint: CGPointMake(63.57, 41.12)];
                [importedLayersPath addCurveToPoint: CGPointMake(67.68, 37.01) controlPoint1: CGPointMake(63.57, 38.85) controlPoint2: CGPointMake(65.41, 37.01)];
                [importedLayersPath addCurveToPoint: CGPointMake(71.79, 41.12) controlPoint1: CGPointMake(69.94, 37.01) controlPoint2: CGPointMake(71.79, 38.85)];
                [importedLayersPath addLineToPoint: CGPointMake(71.79, 44.7)];
                [importedLayersPath addCurveToPoint: CGPointMake(67.68, 48.82) controlPoint1: CGPointMake(71.79, 46.97) controlPoint2: CGPointMake(69.94, 48.82)];
                [importedLayersPath addCurveToPoint: CGPointMake(63.57, 44.7) controlPoint1: CGPointMake(65.41, 48.82) controlPoint2: CGPointMake(63.57, 46.97)];
                [importedLayersPath addLineToPoint: CGPointMake(63.57, 44.7)];
                [importedLayersPath closePath];
                [importedLayersPath moveToPoint: CGPointMake(52.25, 50.86)];
                [importedLayersPath addCurveToPoint: CGPointMake(56.43, 44.7) controlPoint1: CGPointMake(54.69, 49.88) controlPoint2: CGPointMake(56.43, 47.49)];
                [importedLayersPath addLineToPoint: CGPointMake(56.43, 41.12)];
                [importedLayersPath addCurveToPoint: CGPointMake(49.82, 34.5) controlPoint1: CGPointMake(56.43, 37.47) controlPoint2: CGPointMake(53.46, 34.5)];
                [importedLayersPath addCurveToPoint: CGPointMake(43.21, 41.12) controlPoint1: CGPointMake(46.18, 34.5) controlPoint2: CGPointMake(43.21, 37.47)];
                [importedLayersPath addLineToPoint: CGPointMake(43.21, 44.7)];
                [importedLayersPath addCurveToPoint: CGPointMake(47.4, 50.86) controlPoint1: CGPointMake(43.21, 47.49) controlPoint2: CGPointMake(44.95, 49.88)];
                [importedLayersPath addCurveToPoint: CGPointMake(37.86, 62.6) controlPoint1: CGPointMake(41.96, 51.98) controlPoint2: CGPointMake(37.86, 56.82)];
                [importedLayersPath addCurveToPoint: CGPointMake(40.89, 65.64) controlPoint1: CGPointMake(37.86, 64.28) controlPoint2: CGPointMake(39.22, 65.64)];
                [importedLayersPath addLineToPoint: CGPointMake(58.75, 65.64)];
                [importedLayersPath addCurveToPoint: CGPointMake(61.79, 62.6) controlPoint1: CGPointMake(60.42, 65.64) controlPoint2: CGPointMake(61.79, 64.28)];
                [importedLayersPath addCurveToPoint: CGPointMake(52.25, 50.86) controlPoint1: CGPointMake(61.79, 56.82) controlPoint2: CGPointMake(57.68, 51.98)];
                [importedLayersPath addLineToPoint: CGPointMake(52.25, 50.86)];
                [importedLayersPath closePath];
                [importedLayersPath moveToPoint: CGPointMake(45.71, 44.7)];
                [importedLayersPath addLineToPoint: CGPointMake(45.71, 41.12)];
                [importedLayersPath addCurveToPoint: CGPointMake(49.82, 37.01) controlPoint1: CGPointMake(45.71, 38.85) controlPoint2: CGPointMake(47.56, 37.01)];
                [importedLayersPath addCurveToPoint: CGPointMake(53.93, 41.12) controlPoint1: CGPointMake(52.09, 37.01) controlPoint2: CGPointMake(53.93, 38.85)];
                [importedLayersPath addLineToPoint: CGPointMake(53.93, 44.7)];
                [importedLayersPath addCurveToPoint: CGPointMake(49.82, 48.82) controlPoint1: CGPointMake(53.93, 46.97) controlPoint2: CGPointMake(52.09, 48.82)];
                [importedLayersPath addCurveToPoint: CGPointMake(45.71, 44.7) controlPoint1: CGPointMake(47.56, 48.82) controlPoint2: CGPointMake(45.71, 46.97)];
                [importedLayersPath addLineToPoint: CGPointMake(45.71, 44.7)];
                [importedLayersPath closePath];
                [importedLayersPath moveToPoint: CGPointMake(58.75, 63.14)];
                [importedLayersPath addLineToPoint: CGPointMake(40.89, 63.14)];
                [importedLayersPath addCurveToPoint: CGPointMake(40.36, 62.6) controlPoint1: CGPointMake(40.6, 63.14) controlPoint2: CGPointMake(40.36, 62.89)];
                [importedLayersPath addCurveToPoint: CGPointMake(49.82, 53.11) controlPoint1: CGPointMake(40.36, 57.37) controlPoint2: CGPointMake(44.6, 53.11)];
                [importedLayersPath addCurveToPoint: CGPointMake(59.29, 62.6) controlPoint1: CGPointMake(55.04, 53.11) controlPoint2: CGPointMake(59.29, 57.37)];
                [importedLayersPath addCurveToPoint: CGPointMake(58.75, 63.14) controlPoint1: CGPointMake(59.29, 62.89) controlPoint2: CGPointMake(59.04, 63.14)];
                [importedLayersPath addLineToPoint: CGPointMake(58.75, 63.14)];
                [importedLayersPath closePath];
                [importedLayersPath moveToPoint: CGPointMake(39.11, 52.99)];
                [importedLayersPath addCurveToPoint: CGPointMake(34.37, 50.86) controlPoint1: CGPointMake(37.68, 51.93) controlPoint2: CGPointMake(36.07, 51.21)];
                [importedLayersPath addCurveToPoint: CGPointMake(38.57, 44.7) controlPoint1: CGPointMake(36.83, 49.89) controlPoint2: CGPointMake(38.57, 47.5)];
                [importedLayersPath addLineToPoint: CGPointMake(38.57, 41.12)];
                [importedLayersPath addCurveToPoint: CGPointMake(31.96, 34.5) controlPoint1: CGPointMake(38.57, 37.47) controlPoint2: CGPointMake(35.61, 34.5)];
                [importedLayersPath addCurveToPoint: CGPointMake(25.36, 41.12) controlPoint1: CGPointMake(28.32, 34.5) controlPoint2: CGPointMake(25.36, 37.47)];
                [importedLayersPath addLineToPoint: CGPointMake(25.36, 44.7)];
                [importedLayersPath addCurveToPoint: CGPointMake(29.54, 50.86) controlPoint1: CGPointMake(25.36, 47.49) controlPoint2: CGPointMake(27.09, 49.88)];
                [importedLayersPath addCurveToPoint: CGPointMake(20, 62.6) controlPoint1: CGPointMake(24.1, 51.98) controlPoint2: CGPointMake(20, 56.82)];
                [importedLayersPath addCurveToPoint: CGPointMake(23.04, 65.64) controlPoint1: CGPointMake(20, 64.28) controlPoint2: CGPointMake(21.36, 65.64)];
                [importedLayersPath addLineToPoint: CGPointMake(35.85, 65.64)];
                [importedLayersPath addCurveToPoint: CGPointMake(36.4, 65.51) controlPoint1: CGPointMake(36.05, 65.64) controlPoint2: CGPointMake(36.23, 65.59)];
                [importedLayersPath addCurveToPoint: CGPointMake(35.56, 63.14) controlPoint1: CGPointMake(35.95, 64.81) controlPoint2: CGPointMake(35.65, 64.01)];
                [importedLayersPath addLineToPoint: CGPointMake(23.04, 63.14)];
                [importedLayersPath addCurveToPoint: CGPointMake(22.5, 62.6) controlPoint1: CGPointMake(22.75, 63.14) controlPoint2: CGPointMake(22.5, 62.89)];
                [importedLayersPath addCurveToPoint: CGPointMake(31.96, 53.11) controlPoint1: CGPointMake(22.5, 57.37) controlPoint2: CGPointMake(26.75, 53.11)];
                [importedLayersPath addCurveToPoint: CGPointMake(37.61, 55) controlPoint1: CGPointMake(34.01, 53.11) controlPoint2: CGPointMake(35.96, 53.77)];
                [importedLayersPath addCurveToPoint: CGPointMake(37.69, 55.05) controlPoint1: CGPointMake(37.63, 55.02) controlPoint2: CGPointMake(37.66, 55.03)];
                [importedLayersPath addCurveToPoint: CGPointMake(39.18, 53.06) controlPoint1: CGPointMake(38.13, 54.34) controlPoint2: CGPointMake(38.63, 53.68)];
                [importedLayersPath addCurveToPoint: CGPointMake(39.11, 52.99) controlPoint1: CGPointMake(39.15, 53.04) controlPoint2: CGPointMake(39.13, 53.01)];
                [importedLayersPath addLineToPoint: CGPointMake(39.11, 52.99)];
                [importedLayersPath closePath];
                [importedLayersPath moveToPoint: CGPointMake(27.86, 44.7)];
                [importedLayersPath addLineToPoint: CGPointMake(27.86, 41.12)];
                [importedLayersPath addCurveToPoint: CGPointMake(31.96, 37.01) controlPoint1: CGPointMake(27.86, 38.85) controlPoint2: CGPointMake(29.7, 37.01)];
                [importedLayersPath addCurveToPoint: CGPointMake(36.07, 41.12) controlPoint1: CGPointMake(34.23, 37.01) controlPoint2: CGPointMake(36.07, 38.85)];
                [importedLayersPath addLineToPoint: CGPointMake(36.07, 44.7)];
                [importedLayersPath addCurveToPoint: CGPointMake(31.96, 48.82) controlPoint1: CGPointMake(36.07, 46.97) controlPoint2: CGPointMake(34.23, 48.82)];
                [importedLayersPath addCurveToPoint: CGPointMake(27.86, 44.7) controlPoint1: CGPointMake(29.7, 48.82) controlPoint2: CGPointMake(27.86, 46.97)];
                [importedLayersPath addLineToPoint: CGPointMake(27.86, 44.7)];
                [importedLayersPath closePath];
                importedLayersPath.miterLimit = 4;

                importedLayersPath.usesEvenOddFillRule = YES;

                [color9 setFill];
                [importedLayersPath fill];
            }
        }
    }
}

+ (void)drawTimeline
{
    //// Color Declarations
    UIColor* color10 = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];

    //// Page-1
    {
        //// Find-People
        {
            //// Tab-Bar-2
            {
                //// Imported-Layers-3-+-Rectangle-222-+-Rectangle-223-+-Rectangle-224
                {
                    //// timelineIcon Drawing
                    UIBezierPath* timelineIconPath = UIBezierPath.bezierPath;
                    [timelineIconPath moveToPoint: CGPointMake(34.42, 20.1)];
                    [timelineIconPath addCurveToPoint: CGPointMake(33.46, 17.95) controlPoint1: CGPointMake(33.78, 19.43) controlPoint2: CGPointMake(33.46, 18.7)];
                    [timelineIconPath addCurveToPoint: CGPointMake(34.42, 15.81) controlPoint1: CGPointMake(33.46, 17.21) controlPoint2: CGPointMake(33.78, 16.47)];
                    [timelineIconPath addCurveToPoint: CGPointMake(34.93, 15.3) controlPoint1: CGPointMake(34.58, 15.63) controlPoint2: CGPointMake(34.76, 15.47)];
                    [timelineIconPath addCurveToPoint: CGPointMake(35.66, 12.3) controlPoint1: CGPointMake(35.71, 14.43) controlPoint2: CGPointMake(36.11, 13.42)];
                    [timelineIconPath addCurveToPoint: CGPointMake(34.42, 10.43) controlPoint1: CGPointMake(35.38, 11.62) controlPoint2: CGPointMake(34.92, 10.98)];
                    [timelineIconPath addCurveToPoint: CGPointMake(33.98, 6.51) controlPoint1: CGPointMake(33.31, 9.2) controlPoint2: CGPointMake(33.11, 7.8)];
                    [timelineIconPath addCurveToPoint: CGPointMake(35.28, 4.86) controlPoint1: CGPointMake(34.37, 5.93) controlPoint2: CGPointMake(34.93, 5.47)];
                    [timelineIconPath addCurveToPoint: CGPointMake(34.78, 1.11) controlPoint1: CGPointMake(35.94, 3.67) controlPoint2: CGPointMake(35.72, 2.1)];
                    [timelineIconPath addCurveToPoint: CGPointMake(30.67, 0.74) controlPoint1: CGPointMake(33.72, -0.01) controlPoint2: CGPointMake(31.93, -0.06)];
                    [timelineIconPath addCurveToPoint: CGPointMake(28.61, 2.23) controlPoint1: CGPointMake(29.94, 1.2) controlPoint2: CGPointMake(29.43, 1.9)];
                    [timelineIconPath addCurveToPoint: CGPointMake(26.39, 2.08) controlPoint1: CGPointMake(27.87, 2.53) controlPoint2: CGPointMake(27.09, 2.46)];
                    [timelineIconPath addCurveToPoint: CGPointMake(25.21, 1.15) controlPoint1: CGPointMake(25.95, 1.84) controlPoint2: CGPointMake(25.57, 1.51)];
                    [timelineIconPath addCurveToPoint: CGPointMake(20.36, 1.18) controlPoint1: CGPointMake(23.68, -0.39) controlPoint2: CGPointMake(21.9, -0.38)];
                    [timelineIconPath addCurveToPoint: CGPointMake(17.92, 2.43) controlPoint1: CGPointMake(19.53, 2.01) controlPoint2: CGPointMake(18.73, 2.43)];
                    [timelineIconPath addCurveToPoint: CGPointMake(15.49, 1.18) controlPoint1: CGPointMake(17.12, 2.43) controlPoint2: CGPointMake(16.32, 2.01)];
                    [timelineIconPath addCurveToPoint: CGPointMake(10.64, 1.15) controlPoint1: CGPointMake(13.95, -0.38) controlPoint2: CGPointMake(12.17, -0.39)];
                    [timelineIconPath addCurveToPoint: CGPointMake(9.45, 2.08) controlPoint1: CGPointMake(10.28, 1.51) controlPoint2: CGPointMake(9.9, 1.84)];
                    [timelineIconPath addCurveToPoint: CGPointMake(7.24, 2.23) controlPoint1: CGPointMake(8.76, 2.46) controlPoint2: CGPointMake(7.98, 2.53)];
                    [timelineIconPath addCurveToPoint: CGPointMake(5.18, 0.74) controlPoint1: CGPointMake(6.42, 1.9) controlPoint2: CGPointMake(5.91, 1.2)];
                    [timelineIconPath addCurveToPoint: CGPointMake(1.07, 1.11) controlPoint1: CGPointMake(3.92, -0.06) controlPoint2: CGPointMake(2.13, -0.01)];
                    [timelineIconPath addCurveToPoint: CGPointMake(0.57, 4.86) controlPoint1: CGPointMake(0.13, 2.1) controlPoint2: CGPointMake(-0.09, 3.67)];
                    [timelineIconPath addCurveToPoint: CGPointMake(1.87, 6.51) controlPoint1: CGPointMake(0.92, 5.47) controlPoint2: CGPointMake(1.48, 5.93)];
                    [timelineIconPath addCurveToPoint: CGPointMake(1.43, 10.43) controlPoint1: CGPointMake(2.74, 7.8) controlPoint2: CGPointMake(2.54, 9.2)];
                    [timelineIconPath addCurveToPoint: CGPointMake(0.19, 12.3) controlPoint1: CGPointMake(0.93, 10.98) controlPoint2: CGPointMake(0.46, 11.62)];
                    [timelineIconPath addCurveToPoint: CGPointMake(0.92, 15.3) controlPoint1: CGPointMake(-0.26, 13.42) controlPoint2: CGPointMake(0.14, 14.43)];
                    [timelineIconPath addCurveToPoint: CGPointMake(1.43, 15.81) controlPoint1: CGPointMake(1.08, 15.47) controlPoint2: CGPointMake(1.27, 15.63)];
                    [timelineIconPath addCurveToPoint: CGPointMake(2.39, 17.95) controlPoint1: CGPointMake(2.07, 16.47) controlPoint2: CGPointMake(2.39, 17.21)];
                    [timelineIconPath addCurveToPoint: CGPointMake(1.43, 20.1) controlPoint1: CGPointMake(2.39, 18.7) controlPoint2: CGPointMake(2.07, 19.43)];
                    [timelineIconPath addCurveToPoint: CGPointMake(0.92, 20.61) controlPoint1: CGPointMake(1.27, 20.27) controlPoint2: CGPointMake(1.08, 20.43)];
                    [timelineIconPath addCurveToPoint: CGPointMake(0.19, 23.6) controlPoint1: CGPointMake(0.14, 21.47) controlPoint2: CGPointMake(-0.26, 22.48)];
                    [timelineIconPath addCurveToPoint: CGPointMake(1.43, 25.48) controlPoint1: CGPointMake(0.46, 24.29) controlPoint2: CGPointMake(0.93, 24.92)];
                    [timelineIconPath addCurveToPoint: CGPointMake(1.87, 29.39) controlPoint1: CGPointMake(2.54, 26.7) controlPoint2: CGPointMake(2.74, 28.1)];
                    [timelineIconPath addCurveToPoint: CGPointMake(0.57, 31.05) controlPoint1: CGPointMake(1.48, 29.97) controlPoint2: CGPointMake(0.92, 30.43)];
                    [timelineIconPath addCurveToPoint: CGPointMake(1.07, 34.79) controlPoint1: CGPointMake(-0.09, 32.24) controlPoint2: CGPointMake(0.13, 33.8)];
                    [timelineIconPath addCurveToPoint: CGPointMake(5.18, 35.16) controlPoint1: CGPointMake(2.13, 35.91) controlPoint2: CGPointMake(3.92, 35.96)];
                    [timelineIconPath addCurveToPoint: CGPointMake(7.24, 33.67) controlPoint1: CGPointMake(5.91, 34.7) controlPoint2: CGPointMake(6.42, 34)];
                    [timelineIconPath addCurveToPoint: CGPointMake(9.45, 33.83) controlPoint1: CGPointMake(7.98, 33.37) controlPoint2: CGPointMake(8.76, 33.44)];
                    [timelineIconPath addCurveToPoint: CGPointMake(10.64, 34.75) controlPoint1: CGPointMake(9.9, 34.07) controlPoint2: CGPointMake(10.28, 34.4)];
                    [timelineIconPath addCurveToPoint: CGPointMake(15.49, 34.73) controlPoint1: CGPointMake(12.17, 36.3) controlPoint2: CGPointMake(13.95, 36.29)];
                    [timelineIconPath addCurveToPoint: CGPointMake(17.92, 33.47) controlPoint1: CGPointMake(16.32, 33.89) controlPoint2: CGPointMake(17.12, 33.47)];
                    [timelineIconPath addCurveToPoint: CGPointMake(20.36, 34.73) controlPoint1: CGPointMake(18.73, 33.47) controlPoint2: CGPointMake(19.53, 33.89)];
                    [timelineIconPath addCurveToPoint: CGPointMake(25.21, 34.75) controlPoint1: CGPointMake(21.9, 36.29) controlPoint2: CGPointMake(23.68, 36.3)];
                    [timelineIconPath addCurveToPoint: CGPointMake(26.39, 33.83) controlPoint1: CGPointMake(25.57, 34.4) controlPoint2: CGPointMake(25.95, 34.07)];
                    [timelineIconPath addCurveToPoint: CGPointMake(28.61, 33.67) controlPoint1: CGPointMake(27.09, 33.44) controlPoint2: CGPointMake(27.87, 33.37)];
                    [timelineIconPath addCurveToPoint: CGPointMake(30.67, 35.16) controlPoint1: CGPointMake(29.43, 34) controlPoint2: CGPointMake(29.94, 34.7)];
                    [timelineIconPath addCurveToPoint: CGPointMake(34.78, 34.79) controlPoint1: CGPointMake(31.93, 35.96) controlPoint2: CGPointMake(33.72, 35.91)];
                    [timelineIconPath addCurveToPoint: CGPointMake(35.28, 31.05) controlPoint1: CGPointMake(35.72, 33.8) controlPoint2: CGPointMake(35.94, 32.24)];
                    [timelineIconPath addCurveToPoint: CGPointMake(33.98, 29.39) controlPoint1: CGPointMake(34.93, 30.43) controlPoint2: CGPointMake(34.37, 29.97)];
                    [timelineIconPath addCurveToPoint: CGPointMake(34.42, 25.48) controlPoint1: CGPointMake(33.11, 28.1) controlPoint2: CGPointMake(33.31, 26.7)];
                    [timelineIconPath addCurveToPoint: CGPointMake(35.66, 23.6) controlPoint1: CGPointMake(34.92, 24.92) controlPoint2: CGPointMake(35.38, 24.29)];
                    [timelineIconPath addCurveToPoint: CGPointMake(34.93, 20.61) controlPoint1: CGPointMake(36.11, 22.48) controlPoint2: CGPointMake(35.71, 21.47)];
                    [timelineIconPath addCurveToPoint: CGPointMake(34.42, 20.1) controlPoint1: CGPointMake(34.76, 20.43) controlPoint2: CGPointMake(34.58, 20.27)];
                    [timelineIconPath addLineToPoint: CGPointMake(34.42, 20.1)];
                    [timelineIconPath closePath];
                    [timelineIconPath moveToPoint: CGPointMake(6.48, 6.5)];
                    [timelineIconPath addLineToPoint: CGPointMake(29.37, 6.5)];
                    [timelineIconPath addLineToPoint: CGPointMake(29.37, 29.4)];
                    [timelineIconPath addLineToPoint: CGPointMake(6.48, 29.4)];
                    [timelineIconPath addLineToPoint: CGPointMake(6.48, 6.5)];
                    [timelineIconPath closePath];
                    timelineIconPath.miterLimit = 4;

                    timelineIconPath.usesEvenOddFillRule = YES;

                    [color10 setFill];
                    [timelineIconPath fill];
                }
            }
        }
    }
}

#pragma mark Generated Images

+ (UIImage*)imageOfPhoto
{
    if (_imageOfPhoto)
        return _imageOfPhoto;

    UIGraphicsBeginImageContextWithOptions(CGSizeMake(100, 100), NO, 0.0f);
    [InterfaceButtons drawPhoto];

    _imageOfPhoto = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return _imageOfPhoto;
}

+ (UIImage*)imageOfFamilyFriendsIcon
{
    if (_imageOfFamilyFriendsIcon)
        return _imageOfFamilyFriendsIcon;

    UIGraphicsBeginImageContextWithOptions(CGSizeMake(100, 100), NO, 0.0f);
    [InterfaceButtons drawFamilyFriendsIcon];

    _imageOfFamilyFriendsIcon = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return _imageOfFamilyFriendsIcon;
}

+ (UIImage*)imageOfInviteIcon
{
    if (_imageOfInviteIcon)
        return _imageOfInviteIcon;

    UIGraphicsBeginImageContextWithOptions(CGSizeMake(100, 100), NO, 0.0f);
    [InterfaceButtons drawInviteIcon];

    _imageOfInviteIcon = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return _imageOfInviteIcon;
}

+ (UIImage*)imageOfTimeline
{
    if (_imageOfTimeline)
        return _imageOfTimeline;

    UIGraphicsBeginImageContextWithOptions(CGSizeMake(36, 36), NO, 0.0f);
    [InterfaceButtons drawTimeline];

    _imageOfTimeline = [UIGraphicsGetImageFromCurrentImageContext() imageWithRenderingMode: UIImageRenderingModeAlwaysOriginal];
    UIGraphicsEndImageContext();

    return _imageOfTimeline;
}

#pragma mark Customization Infrastructure

- (void)setPhotoTargets: (NSArray*)photoTargets
{
    _photoTargets = photoTargets;

    for (id target in self.photoTargets)
        [target setImage: InterfaceButtons.imageOfPhoto];
}

- (void)setFamilyFriendsIconTargets: (NSArray*)familyFriendsIconTargets
{
    _familyFriendsIconTargets = familyFriendsIconTargets;

    for (id target in self.familyFriendsIconTargets)
        [target setImage: InterfaceButtons.imageOfFamilyFriendsIcon];
}

- (void)setInviteIconTargets: (NSArray*)inviteIconTargets
{
    _inviteIconTargets = inviteIconTargets;

    for (id target in self.inviteIconTargets)
        [target setImage: InterfaceButtons.imageOfInviteIcon];
}

- (void)setTimelineTargets: (NSArray*)timelineTargets
{
    _timelineTargets = timelineTargets;

    for (id target in self.timelineTargets)
        [target setImage: InterfaceButtons.imageOfTimeline];
}


@end
